# Generated by Django 4.0 on 2022-01-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_reated'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='ulubione_filmy',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Movie'),
        ),
    ]
