# Generated by Django 4.0 on 2022-01-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_youtube_link'),
        ('accounts', '0002_alter_user_info_ulubione_filmy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='ulubione_filmy',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
    ]
