# Generated by Django 4.0 on 2022-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_info_ulubione_filmy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
