# Generated by Django 4.0 on 2022-01-11 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('model_img', models.ImageField(blank=True, upload_to='movies_photos')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('scenariusz', models.CharField(blank=True, max_length=50, null=True)),
                ('gatunek', models.CharField(blank=True, max_length=50, null=True)),
                ('kraj', models.CharField(blank=True, max_length=50, null=True)),
                ('data_premiery', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='auth.user')),
                ('reated', models.ManyToManyField(blank=True, default=None, related_name='oceniony', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
