# Generated by Django 4.0 on 2022-01-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_short_desc_alter_movie_model_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='reated',
        ),
    ]
