# Generated by Django 4.0 on 2022-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtube_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
