# Generated by Django 4.0 on 2022-01-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='youtube_link',
        ),
    ]
